import{a as B,S as $,i as f}from"./assets/vendor-xpOxgMII.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const A="https://pixabay.com/api/",O="23862309-642a8b5e3128a5abba1046e7c";async function y(t,o){const s={key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await B.get(A,{params:s})).data}const L=document.querySelector(".gallery"),b=document.querySelector(".loader"),S=document.querySelector(".load-more"),F=new $(".gallery a",{captionsData:"alt",captionDelay:250});function w(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:P,downloads:R})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
        </a>

        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${P}</p>
          <p class="info-item"><b>Downloads</b> ${R}</p>
        </div>
      </li>
    `).join("");L.insertAdjacentHTML("beforeend",o),F.refresh()}function x(){L.innerHTML=""}function E(){b.classList.remove("is-hidden")}function M(){b.classList.add("is-hidden")}function q(){S.classList.remove("is-hidden")}function l(){S.classList.add("is-hidden")}const g=document.querySelector(".form"),p=document.querySelector(".load-more"),d=document.querySelector(".no-results"),u=document.querySelector(".end-message");let m="",i=1,c=0;const v=15;g&&g.addEventListener("submit",H);p&&p.addEventListener("click",N);l();async function H(t){t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(o===""){f.error({message:"Please enter a search query.",position:"topRight"});return}m=o,i=1,c=0,_(),D(),x(),l(),E();try{const s=await y(m,i);if(c=s.totalHits,!s.hits||s.hits.length===0){C(),l();return}w(s.hits),i*v>=c?h():q()}catch{f.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{M()}}async function N(){i+=1,l(),E();try{const t=await y(m,i);if(!t.hits||t.hits.length===0){h();return}w(t.hits),G(),i*v>=c?h():q()}catch{f.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{M()}}function _(){d&&d.classList.add("is-hidden")}function C(){d&&d.classList.remove("is-hidden")}function D(){u&&u.classList.add("is-hidden")}function z(){u&&u.classList.remove("is-hidden")}function h(){l(),z()}function G(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
